### ISSUE TITLE
Runtime error 217 at 004BA944 (Delphi XE5)

### ISSUE THREAD

**Issue by markhumphreysjhc** [RomanYankovsky/DelphiSpec#12]
I have downloaded and compiled the DelphiSpecDemo project, but get the error shown above.

I haven't changed any settings, options, etc. 

Is there anything else I can add that would help investigate

Thanks

**Comment by RomanYankovsky** [comment]
@markhumphreysjhc please download the latest sources and try again. This issue should be fixed.
